### ISSUE TITLE
Wrong range in GetSubmodelsResult/result "metamodel-part2"

### ISSUE THREAD

**Issue by geso02** [admin-shell-io/aas-specs-api#216]
# What happens?

The property "result" of [GetSubmodelsResult](https://app.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0.1#/components/schemas/GetSubmodelsResult) has a range with items of type [SubmodelElement](https://app.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1#/components/schemas/SubmodelElement). This differs from the current implementation of the submodel repository. 

When invoking [GetAllSubmodels](https://app.swaggerhub.com/apis/Plattform_i40/SubmodelRepositoryServiceSpecification/V3.0.1_SSP-001#/Submodel%20Repository%20API/GetAllSubmodelElements) I get a [Property](https://app.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1#/components/schemas/Property) in my specific test setup that is a "subtype" of  [SubmodelElement_choice](https://app.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1#/components/schemas/SubmodelElement_choice) (more details in the next sections) not of [SubmodelElement](https://app.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1#/components/schemas/SubmodelElement).

My parser fails to deserialize the property "value" in this object as this is not defined in SubmodelElement.

# Why is this wrong?

We just have an allOf implementation in SubmodelElement. All those referenced objects do not contain a "value" property.

```
    SubmodelElement:
      allOf:
      - "$ref": "#/components/schemas/Referable"
      - "$ref": "#/components/schemas/HasSemantics"
      - "$ref": "#/components/schemas/Qualifiable"
      - "$ref": "#/components/schemas/HasDataSpecification"
```

A oneOf implementation would be more what we want here, like [SubmodelElement_choice](https://app.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1#/components/schemas/SubmodelElement_choice):

```
    SubmodelElement_choice:
      oneOf:
      - "$ref": "#/components/schemas/RelationshipElement"
      - "$ref": "#/components/schemas/AnnotatedRelationshipElement"
      - "$ref": "#/components/schemas/MultiLanguageProperty"
      - "$ref": "#/components/schemas/Operation"
      - "$ref": "#/components/schemas/Property"
      ...
```

# How should it be fixed?

We should use [SubmodelElement_choice](https://app.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1#/components/schemas/SubmodelElement_choice) (Or a new, identical definition with a different name like AbstractSubmodelElement).

There are also other "result"-objects with range SubmodelElement in part2. It's also not correct at these positions.
...

- [x ] I have signed the required Developer Certificate of Origin ([DCO](https://developercertificate.org)) already.
