### ISSUE TITLE
Consistent Pattern for OpenAPI Server Clauses

### ISSUE THREAD

**Issue by sebbader-sap** [admin-shell-io/aas-specs-api#364]
**Problem** 

We have inconsistent content for the servers in the OpenAPI files, see A and B.

A) Example https://app.swaggerhub.com/apis/Plattform_i40/AssetAdministrationShellRepositoryServiceSpecification/V3.0.3_SSP-001#/servers :
```
servers:
- url: '{protocol}://{host_name}:{port}/api/{version_prefix}'
  variables:
    protocol:
      description: 'Allows access through http and https (recommended)'
      enum:
        - 'http'
        - 'https'
      default: 'https'
    host_name:
      default: admin-shell.io
      description: 'Hostname of server hosting the api'
    port:
      enum:
        - '80'
        - '443'
      default: '443'
      description: '80 is default for http, 443 for https'
    version_prefix:
      enum:
        - 'v3.0'
      default: v3.0
```
Problem: The `/api/` path segment is not mandatory, neither is the `version_prefix` anymore.

B) Example https://github.com/admin-shell-io/aas-specs-api/blob/98a9aea6fb3adbd0f94cd202e215d9474b8ed3c6/DiscoveryServiceSpecification/V3.0_SSP-002.yaml#L16
```

servers:
- url: 'https://admin-shell.io/api/v3.1'
- url: 'https://example.com/'
```
Problem: It's not completely clear that the two entries are only examples, even though the informed reader very well understands it. Furthermore, it might irritate developers that expect the previously used pattern A...

**Question**
Which pattern is the _right one_ for the AAS? Is there even a third option?
