### ISSUE TITLE
Missing Discriminator for DataSpecificationContent

### ISSUE THREAD

**Issue by sebbader-sap** [admin-shell-io/aas-specs-api#97]
# What?

No defined discriminator attribute for DataSpecificationContent. 

# How?

Use `modelType` similar to the SubmodelElements.
```
DataSpecificationContent:
   type: object
   discriminator:
      propertyname: modeltype
```

This issue relates to finding `DFKI#04`.
