### ISSUE TITLE
Duplicate Declaration of 'extensions' in the Descriptor class

### ISSUE THREAD

**Issue by sebbader-sap** [admin-shell-io/aas-specs-api#99]
# What?

```
    Descriptor: 
      example: ...
      allOf:
        *- $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0#/components/schemas/HasExtensions"*
      properties: 
        description: 
          type: array
          items:
            $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0#/components/schemas/LangStringTextType"
        displayName: 
          type: array
          items:
            $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0#/components/schemas/LangStringNameType"
          *extensions:
             type: array
             items:
                "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0#/components/schemas/Extension"
             minItems: 1*
      type: object
```

# How?

```
    Descriptor: 
      example: ...
      properties: 
        description: 
          type: array
          items:
            $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0#/components/schemas/LangStringTextType"
        displayName: 
          type: array
          items:
            $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0#/components/schemas/LangStringNameType"
          *extensions:
             type: array
             items:
                "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0#/components/schemas/Extension"
             minItems: 1*
      type: object
```

This issue relates to finding `DFKI#06`.
